site_name: RESIF 2.0 Documentation
repo_url: https://gitlab.uni.lu/ULHPC/resif
pages:
- Home: 'index.md'
- Getting Started:
  - Requirements:
    - Overview: 'tools/index.md'
    - Lmod: 'tools/lmod.md'
    - Easybuild: 'tools/easybuild.md'
  - Installation: 'install.md'
  - Configuration Variables: 'variables.md'
  - Module Naming Scheme: 'mns.md'
  - Easybuild Sources: 'ebsources.md'
  - Software Sets: 'software_sets.md'
- Command-Line Interface (CLI): 'cli/index.md'
- Documentation:
  - 'Overview and Underlying tools': 'tools/index.md'
  - 'Layout and Versioning': 'layout-and-versioning.md'
- Authors/Contributors: 'AUTHORS.md'
theme: readthedocs
