site_name: RESIF 2.0 Documentation
repo_url: https://gitlab.uni.lu/ULHPC/resif
pages:
- Home: 'index.md'
- Getting Started:
  - Installation: 'install.md'
- Command-Line Interface (CLI):
  - Overview: 'cli/index.md'
- Documentation:
  - 'Overview and Underlying tools': 'tools/index.md'
  - 'Layout and Versioning': 'layout-and-versioning.md'
theme: readthedocs
